jwt:
    secret: Zy7w8tA!Qw3rTy6*Pl0KzX9cVbNm2Ee
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG