jwt:
    secret: djhfjklaadfjalkdfhlKFALKJFJLAKFHDLKJfhlkjdfhalkjfhalkjdfhdalkjfhalskjfhadsjlkfahsljkfdh
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG